/* Read cookbook columns separately; photographs never become ingredient/method text. */
function photoParagraphs(data,width,height){return (data.blocks||[]).flatMap(b=>b.paragraphs||[]).filter(p=>p.confidence>=45&&/[a-z]{3}/i.test(p.text)&&p.bbox.y0<height*.94&&p.bbox.x1-p.bbox.x0>width*.025)}
function photoColumns(paragraphs,width){
 let lines=paragraphs.flatMap(p=>p.lines||[]).filter(l=>l.confidence>=55&&/[a-z]{3}/i.test(l.text)&&l.bbox.x1-l.bbox.x0>width*.035),groups=[];
 for(let l of lines){let g=groups.find(g=>Math.abs(g.x-l.bbox.x0)<width*.035);if(!g)groups.push(g={x:l.bbox.x0,lines:[]});g.lines.push(l);g.x=g.lines.reduce((s,l)=>s+l.bbox.x0,0)/g.lines.length}
 let pairs=[];for(let a of groups)for(let b of groups)if(b.x-a.x>width*.18&&a.lines.length>=4&&b.lines.length>=4)pairs.push({a,b,score:a.lines.length+b.lines.length});pairs.sort((a,b)=>b.score-a.score);if(!pairs.length)return null;
 let {a,b}=pairs[0],left=lines.filter(l=>l.bbox.x0<b.x-width*.06&&l.bbox.x1<b.x),ends=left.map(l=>l.bbox.x1).sort((a,b)=>a-b),edge=ends[Math.floor((ends.length-1)*.95)];if(!edge||b.x-edge<width*.015)return null;
 let split=(edge+b.x)/2,columns=[paragraphs.filter(p=>p.bbox.x1<split+width*.02),paragraphs.filter(p=>p.bbox.x0>split-width*.02)];let scores=columns.map(c=>c.flatMap(p=>p.lines||[]).filter(l=>/^\s*(?:\d|[½¼¾⅓⅔]|[Il|]\s*(?:tea|table)spoon)/i.test(l.text)).length);if(Math.max(...scores)<3)return null;return {split,columns,ingredientSide:scores[1]>scores[0]?1:0}
}
function photoCanvas(image){let canvas=document.createElement('canvas'),scale=Math.min(1,3200/Math.max(image.width,image.height));canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);return canvas}
function normalizedPhoto(canvas){let w=canvas.width,h=canvas.height,ctx=canvas.getContext('2d'),data=ctx.getImageData(0,0,w,h),a=data.data,integral=new Float64Array((w+1)*(h+1));for(let y=0;y<h;y++){let row=0;for(let x=0;x<w;x++){let i=(y*w+x)*4,v=.299*a[i]+.587*a[i+1]+.114*a[i+2];a[i]=v;row+=v;integral[(y+1)*(w+1)+x+1]=integral[y*(w+1)+x+1]+row}}let r=Math.max(12,Math.round(w/90));for(let y=0;y<h;y++)for(let x=0;x<w;x++){let x0=Math.max(0,x-r),x1=Math.min(w,x+r+1),y0=Math.max(0,y-r),y1=Math.min(h,y+r+1),mean=(integral[y1*(w+1)+x1]-integral[y0*(w+1)+x1]-integral[y1*(w+1)+x0]+integral[y0*(w+1)+x0])/((x1-x0)*(y1-y0)),i=(y*w+x)*4,v=Math.max(0,Math.min(255,(a[i]-mean+30)*8));a[i]=a[i+1]=a[i+2]=v;a[i+3]=255}let out=document.createElement('canvas');out.width=w;out.height=h;out.getContext('2d').putImageData(data,0,0);return out}
function straightenPhotoRegion(source,box){let pad=20,x0=Math.max(0,box.x0-pad),y0=Math.max(0,box.y0-pad),w=Math.min(source.width-x0,box.x1-x0+pad),h=Math.min(source.height-y0,box.y1-y0+pad),small=document.createElement('canvas'),scale=Math.min(1,700/Math.max(w,h));small.width=Math.ceil(w*scale);small.height=Math.ceil(h*scale);small.getContext('2d').drawImage(source,x0,y0,w,h,0,0,small.width,small.height);let a=small.getContext('2d').getImageData(0,0,small.width,small.height).data,points=[];for(let y=8;y<small.height-8;y+=2)for(let x=8;x<small.width-8;x+=2)if(a[(y*small.width+x)*4]<90)points.push([x,y]);let best=0,angle=0;for(let deg=-12;deg<=12;deg+=.25){let rows=new Uint32Array(small.height+400),slope=Math.tan(deg*Math.PI/180);for(let [x,y]of points)rows[Math.round(y+slope*(x-small.width/2))+200]++;let score=rows.reduce((s,n)=>s+n*n,0);if(score>best){best=score;angle=deg*Math.PI/180}}let out=document.createElement('canvas');out.width=Math.ceil(w+Math.abs(h*Math.sin(angle))+40);out.height=Math.ceil(h+Math.abs(w*Math.sin(angle))+40);let ctx=out.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,out.width,out.height);ctx.translate(out.width/2,out.height/2);ctx.rotate(angle);ctx.drawImage(source,x0,y0,w,h,-w/2,-h/2,w,h);return out}
function photoBox(parts){return {x0:Math.min(...parts.map(p=>p.bbox.x0)),x1:Math.max(...parts.map(p=>p.bbox.x1)),y0:Math.min(...parts.map(p=>p.bbox.y0)),y1:Math.max(...parts.map(p=>p.bbox.y1))}}
function cleanPhotoText(text){return text.replace(/\b[Il|]\s*tea?spoon/gi,'1 teaspoon').replace(/\b[Il|]\s*table?spoon/gi,'1 tablespoon').replace(/\b[VyY]2\b/g,'½').replace(/\b(\d+)\s*t[0o]\s*(\d+)\b/gi,'$1 to $2').replace(/([a-z])-\n([a-z])/gi,'$1$2').replace(/^\|\s*(?=\d|unsalted)/gm,'').replace(/all-purpose four/gi,'all-purpose flour').replace(/Maldon sat\b/gi,'Maldon salt')}
function photoIngredientText(data,parts){let lines=parts.flatMap(p=>p.lines||[]).sort((a,b)=>a.bbox.y0-b.bbox.y0),out=[];for(let l of lines){let text=cleanPhotoText(l.text.trim());if(!text||text===text.toUpperCase()&&/[A-Z]/.test(text)||/^(serves|servings|yield|makes)\b/i.test(text))continue;let w=l.words?.[0];if(/^\d{4,}\s+(?!g\b|grams?\b|ml\b|millilit)/i.test(text))text='[check amount] '+text;else if(w&&(w.confidence<80||/pounds?|lbs?/.test(text))&&/^\d+\s+(?:pounds?|lbs?|cups?)\b/i.test(text))text='[check amount] '+text;out.push(text)}return out.join('\n')}
async function readCookbookPhoto(worker,image,report){let bitmap=await createImageBitmap(image),canvas;try{canvas=photoCanvas(bitmap)}finally{bitmap.close()}let initial=(await worker.recognize(canvas,{tessedit_pageseg_mode:'3'},{text:true,blocks:true})).data,parts=photoParagraphs(initial,canvas.width,canvas.height),layout=photoColumns(parts,canvas.width);if(!layout){let sparse=(await worker.recognize(canvas,{tessedit_pageseg_mode:'11'},{text:true,blocks:true})).data;let sparseParts=photoParagraphs(sparse,canvas.width,canvas.height),sparseLayout=photoColumns(sparseParts,canvas.width);if(sparseLayout){initial=sparse;parts=sparseParts;layout=sparseLayout}}if(!layout)return cleanPhotoText(initial.text);report('Reading cookbook columns…');let norm=normalizedPhoto(canvas),ingredients=layout.columns[layout.ingredientSide],methods=layout.columns[1-layout.ingredientSide],meta=parts.filter(p=>/^(serves|servings|yield|makes)\b/i.test(p.text.trim())),metadata=meta.map(p=>p.text.trim()).join('\n'),header='';
 if(meta.length){let m=photoBox(meta);if(m.y0>canvas.height*.08){let box={x0:Math.min(m.x0,...ingredients.map(p=>p.bbox.x0)),x1:Math.max(...parts.map(p=>p.bbox.x1)),y0:canvas.height*.035,y1:m.y0-20};header=(await worker.recognize(straightenPhotoRegion(norm,box),{tessedit_pageseg_mode:'6'})).data.text.replace(/^[|\s]+/gm,'')}}
 let ingredientText=photoIngredientText(initial,ingredients),methodText=[],notes=[],active=false;
 if(!meta.length){let box=photoBox(methods),other=photoBox(ingredients);box.y0=Math.max(0,Math.min(box.y0,other.y0)-canvas.height*.04);box.x0=Math.max(0,box.x0-canvas.width*.025);let value=cleanPhotoText((await worker.recognize(straightenPhotoRegion(norm,box),{tessedit_pageseg_mode:'6'})).data.text);methodText=value.trim().split(/\n\s*\n/).map(t=>t.replace(/\n/g,' '))}
 else for(let p of methods.sort((a,b)=>a.bbox.y0-b.bbox.y0)){if(p.bbox.y0<canvas.height*.15||meta.includes(p))continue;let text=cleanPhotoText(p.text.trim());if(/^(make|cook|prep|to serve|heat|add|using|sear|serve|in a|mix|combine|stir|whisk|bake|season|remove|transfer|sprinkle|arrange|scatter|\d+[.)])\b/i.test(text))active=true;if(!active){notes.push(text);continue}if((/^(until|at a|then|each|coat|smoke|pepper|excess|high heat|livers|ready|as they|while|sprinkle)/i.test(text)||text.split(/\s+/).length<5)&&methodText.length)methodText[methodText.length-1]+=' '+text.replace(/\n/g,' ');else methodText.push(text.replace(/\n/g,' '))}
let titleLines=header.trim().split('\n').filter(Boolean);if(titleLines.length>1)notes.unshift(titleLines.slice(1).join(' '));
 return [titleLines[0]||'',metadata,'Ingredients',ingredientText,'Method',...methodText.map((t,i)=>(i+1)+'. '+t),...(notes.length?['Notes',...notes]:[])].filter(Boolean).join('\n')}
